site_name: Kidgell Stories
nav:
    - Home: index.md
    - About: about.md
    - Background: background.md
    - Suggested Topics: suggestions.md
    - East London: eastlondon.md
    - Kimberley: kimberley.md
    - Paddock: paddock.md
    - Transkei: transkei.md
theme:
    name: readthedocs
    highlightjs: true
#	hljs_languages:
#        - yaml
#        - rust
   